Sprint3
ClevertecFrontendLab/radomir-radionov pull request #1
Opened 2023-02-12 22:57 UTC by radomir-radionov

2023-02-12 23:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 25%.
Общее количество тестов: 4.
Количество непройденных тестов: 3.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676242885/main-loading.png)

2023-02-12 23:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 25%.
Общее количество тестов: 4.
Количество непройденных тестов: 3.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676243964/main-loading.png)

2023-02-12 23:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 25%.
Общее количество тестов: 4.
Количество непройденных тестов: 3.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676244784/main-loading.png)

2023-02-12 23:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 25%.
Общее количество тестов: 4.
Количество непройденных тестов: 3.
***
**Get books test -- ErrorBookId -- bookId-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/Get%20books%20test%20--%20ErrorBookId%20--%20bookId-error%20(failed).png)
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245040/main-loading.png)

2023-02-12 23:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676245736/main-loading.png)

2023-02-13 00:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676247539/main-loading.png)

2023-02-13 12:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676291652/main-loading.png)

2023-02-13 15:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- ErrorMain -- main-error (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/Get%20books%20test%20--%20ErrorMain%20--%20main-error%20(failed).png)
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/bookId-sucess.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676301742/main-loading.png)

2023-02-13 19:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676317101/main-loading.png)

2023-02-13 22:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676327775/main-loading.png)

2023-02-14 10:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369177/main-loading.png)

2023-02-14 10:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369634/main-loading.png)

2023-02-14 10:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676369830/main-loading.png)

2023-02-14 14:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676386499/main-loading.png)

2023-02-14 15:05 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218776475-3d0caa39-f172-4089-8891-3b3d4fd68cde.png)
если ошибка то названия конкретной категории тут нет

2023-02-14 15:06 UTC, radomir-radionov commented
![image](https://user-images.githubusercontent.com/66359081/218776944-30ecbd7e-e932-400d-aa7f-a2a7ed026889.png)
 это в макете

2023-02-14 15:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676387777/main-loading.png)

2023-02-14 15:34 UTC, vvikota requested changes

2023-02-14 15:34 UTC, vvikota commented on src/components/CategoriesList/СategoryItem/СategoryItem.tsx
> +  // let currentdataTestId = dataTestId;
удалить по всему приложению лишний закомментированный код

2023-02-14 15:34 UTC, vvikota commented on src/components/CategoriesList/data.ts
> +
тут не совсем правильно , не стоит отталкиваться при роутинге от конкретных названий категорий,
а что будет если к вам придет категория которой нет в списке?

2023-02-14 15:34 UTC, vvikota commented on src/components/FeedbackList/FeedbackList.tsx
> +            {comments.map((comment) => {
тут не нужен return и фигурные скобки

2023-02-14 15:34 UTC, vvikota commented on src/components/FeedbackList/data.ts
> +const usersFeedback = [
это лишнее , комментарии теперь приходят с сервера

2023-02-14 15:34 UTC, vvikota commented on src/modules/BooksList/BookItemLong/BookItemLong.tsx
> +            {authors.map((author) => {
return не нужен

2023-02-14 15:34 UTC, vvikota commented on src/modules/BooksList/data.ts
> +const booksData = [
эти данные теперь приходят с сервера, нужно удалить

2023-02-14 15:34 UTC, vvikota commented on src/redux/modal/selectors.ts
> +const modalState = (state: RootState) => {
если стрелочная  функция возвращает одно выражение то используйте краткий синтаксис: const func = x => x * x;

2023-02-14 15:39 UTC, radomir-radionov commented on src/components/CategoriesList/data.ts
> +
это  старое, сейчас серва данные

2023-02-14 15:39 UTC, radomir-radionov commented on src/components/CategoriesList/СategoryItem/СategoryItem.tsx
> +  // let currentdataTestId = dataTestId;
+

2023-02-14 15:40 UTC, radomir-radionov commented on src/modules/BooksList/data.ts
> +const booksData = [
+

2023-02-14 15:42 UTC, radomir-radionov commented on src/redux/modal/selectors.ts
> +const modalState = (state: RootState) => {
eslint rule

2023-02-14 15:43 UTC, radomir-radionov commented on src/components/FeedbackList/data.ts
> +const usersFeedback = [
+

2023-02-14 15:52 UTC, vvikota commented on src/components/CategoriesList/data.ts
> +
тогда удаляйте если это лишнее

2023-02-14 15:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390015/main-loading.png)

2023-02-14 15:54 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218789447-a5260342-830e-41e4-8e56-6a57023261f3.png)
вот тут не нужно указания количества

2023-02-14 16:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/radomir-radionov/1676390797/main-loading.png)

2023-02-14 16:11 UTC, vvikota approved these changes

2023-02-14 16:13 UTC, merged